-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 00:15:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_Habbib
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_Habbib` ;

-- -----------------------------------------------------
-- Schema db_Habbib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Habbib` DEFAULT CHARACTER SET utf8 ;
USE `db_Habbib` ;

-- -----------------------------------------------------
-- Table `db_Habbib`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Habbib`.`Endereco` (
  `ID_Endereco` INT NOT NULL AUTO_INCREMENT,
  `CEP` INT NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  `Número` INT NULL,
  `Complemento` VARCHAR(255) NULL,
  `Bairro` VARCHAR(255) NOT NULL,
  `Cidade` VARCHAR(255) NOT NULL,
  `UF` ENUM('SP', 'RJ', 'AM', 'PE') NOT NULL,
  PRIMARY KEY (`ID_Endereco`),
  UNIQUE INDEX `ID_Endereco_UNIQUE` (`ID_Endereco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Habbib`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Habbib`.`Instituicao` (
  `idInstituicao` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `CNPJ` VARCHAR(15) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Tipo` ENUM('Particular', 'Privado') CHARACTER SET 'utf8' NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `Endereco_ID_Endereco` INT NOT NULL,
  PRIMARY KEY (`idInstituicao`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC),
  INDEX `fk_Instituicao_Endereco1_idx` (`Endereco_ID_Endereco` ASC),
  CONSTRAINT `fk_Instituicao_Endereco1`
    FOREIGN KEY (`Endereco_ID_Endereco`)
    REFERENCES `db_Habbib`.`Endereco` (`ID_Endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Habbib`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Habbib`.`Paciente` (
  `ID_Paciente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(225) NOT NULL,
  `Sobrenome` VARCHAR(255) NULL,
  `CPF` INT NOT NULL,
  `Data_Nasc` DATE NOT NULL,
  `Genero` ENUM('Masculino', 'Feminino') NOT NULL,
  `CID` VARCHAR(255) NOT NULL,
  `Instituicao_idInstituicao` INT NOT NULL,
  PRIMARY KEY (`ID_Paciente`, `Instituicao_idInstituicao`),
  UNIQUE INDEX `ID_Endereco_UNIQUE` (`ID_Paciente` ASC),
  INDEX `fk_Paciente_Instituicao1_idx` (`Instituicao_idInstituicao` ASC),
  CONSTRAINT `fk_Paciente_Instituicao1`
    FOREIGN KEY (`Instituicao_idInstituicao`)
    REFERENCES `db_Habbib`.`Instituicao` (`idInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '						';


-- -----------------------------------------------------
-- Table `db_Habbib`.`Leito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Habbib`.`Leito` (
  `idLeito` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('UTI', 'Pediatria', 'Enfermaria') NOT NULL,
  `Status` ENUM('Disponivel', 'Ocupado') NOT NULL,
  `Instituicao_idInstituicao` INT NOT NULL,
  PRIMARY KEY (`idLeito`),
  INDEX `fk_Leito_Instituicao1_idx` (`Instituicao_idInstituicao` ASC),
  CONSTRAINT `fk_Leito_Instituicao1`
    FOREIGN KEY (`Instituicao_idInstituicao`)
    REFERENCES `db_Habbib`.`Instituicao` (`idInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Habbib`.`Solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Habbib`.`Solicitacao` (
  `id_Solicitacao` INT NOT NULL AUTO_INCREMENT,
  `Status` ENUM('Em andamento', 'Aprovado', 'Reprovado', 'Aguardando Aprovaçao') NOT NULL,
  `Descricao` VARCHAR(255) NULL,
  `Paciente_ID_Paciente` INT NOT NULL,
  `Leito_idLeito` INT NOT NULL,
  `Leito_Instituicao_idInstituicao` INT NOT NULL,
  PRIMARY KEY (`id_Solicitacao`, `Paciente_ID_Paciente`),
  INDEX `fk_Solicitacao_Paciente1_idx` (`Paciente_ID_Paciente` ASC),
  INDEX `fk_Solicitacao_Leito1_idx` (`Leito_idLeito` ASC, `Leito_Instituicao_idInstituicao` ASC),
  CONSTRAINT `fk_Solicitacao_Paciente1`
    FOREIGN KEY (`Paciente_ID_Paciente`)
    REFERENCES `db_Habbib`.`Paciente` (`ID_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitacao_Leito1`
    FOREIGN KEY (`Leito_idLeito`)
    REFERENCES `db_Habbib`.`Leito` (`idLeito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
